const tintColorLight = '#007AFF';
const tintColorDark = '#0A84FF';

export default {
  light: {
    text: '#333333',
    background: '#f5f5f5',
    card: '#FFFFFF',
    cardShadow: '#000000',
    tint: tintColorLight,
    tabIconDefault: '#999999',
    tabIconSelected: tintColorLight,
    border: '#DDDDDD',
    inputBackground: '#f9f9f9',
    resultBackground: '#f0f8ff',
    infoBackground: '#f0f8ff',
    buttonBackground: '#f0f0f0',
    buttonText: '#555555',
    primaryButton: tintColorLight,
    primaryButtonText: '#FFFFFF',
    historyText: '#444444',
    historyArrow: '#999999',
    historyBorder: '#EEEEEE',
  },
  dark: {
    text: '#E0E0E0',
    background: '#121212',
    card: '#1E1E1E',
    cardShadow: '#000000',
    tint: tintColorDark,
    tabIconDefault: '#777777',
    tabIconSelected: tintColorDark,
    border: '#333333',
    inputBackground: '#2A2A2A',
    resultBackground: '#1A2A3A',
    infoBackground: '#1A2A3A',
    buttonBackground: '#2A2A2A',
    buttonText: '#BBBBBB',
    primaryButton: tintColorDark,
    primaryButtonText: '#FFFFFF',
    historyText: '#BBBBBB',
    historyArrow: '#777777',
    historyBorder: '#333333',
  },
};